version: '3.8'

services:
  # Backend Service
  backend:
    build: ./backend
    container_name: authdb-backend
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=${MONGODB_URL} # Read from .env file or shell environment
      - DB_NAME=authdb
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SECRET_KEY=supersecretkey # Change this in production
    volumes:
       - ./backend:/app # Hot reload for dev

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: authdb-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
